### ISSUE TITLE
Frame Generation will not be enabled when the resolution is below 720p, and artifacts become severe when the frame rate is below 30fps.

### ISSUE THREAD

**Issue by bubuqing99** [MK-JH/MK-JH_Mpv-Fluid-Motion-Frames#3]
Thank you so much for your contribution—your program is truly amazing.

Before this, I tried SPV and Bluesky Frame Rate Converter, but neither of them worked as well or as perfectly as MK-JH_Mpv-Fluid-Motion-Frames.

Now, I’ve encountered an issue: when I tested videos at 240p and 480p, Frame Generation was not enabled, and I’m not sure if this is a bug.

Also, when the frame rate drops below 30fps, the artifacts become severe, especially in videos with windows.

Thank you very much.

![image](https://github.com/user-attachments/assets/815194c6-c0aa-4939-b9e5-de6fd95d42da)
![image](https://github.com/user-attachments/assets/5867ebce-1020-496f-9073-5e3ebd6613af)

**Comment by MK-JH** [comment]
> Thank you so much for your contribution—your program is truly amazing.
> 
> Before this, I tried SPV and Bluesky Frame Rate Converter, but neither of them worked as well or as perfectly as MK-JH_Mpv-Fluid-Motion-Frames.
> 
> Now, I’ve encountered an issue: when I tested videos at 240p and 480p, Frame Generation was not enabled, and I’m not sure if this is a bug.
> 
> Also, when the frame rate drops below 30fps, the artifacts become severe, especially in videos with windows.
> 
> Thank you very much.
> 
> ![image](https://private-user-images.githubusercontent.com/57699051/383852255-815194c6-c0aa-4939-b9e5-de6fd95d42da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MzkwMTgsIm5iZiI6MTczMTQzODcxOCwicGF0aCI6Ii81NzY5OTA1MS8zODM4NTIyNTUtODE1MTk0YzYtYzBhYS00OTM5LWI5ZTUtZGU2ZmQ5NWQ0MmRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDE5MTE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwNTU1MGY2NDRiODkxNGE4MDM5Yjc5MzlmNGNlMjlmOWJkMzViOWE3Y2E3N2E0ZTY1ZDUwY2JhNzU0NzcxNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nNwMuBti1Cg5c8n8lX3K5ZhzuFGYSsptRuT_0Vdd-VQ) ![image](https://private-user-images.githubusercontent.com/57699051/383852267-5867ebce-1020-496f-9073-5e3ebd6613af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MzkwMTgsIm5iZiI6MTczMTQzODcxOCwicGF0aCI6Ii81NzY5OTA1MS8zODM4NTIyNjctNTg2N2ViY2UtMTAyMC00OTZmLTkwNzMtNWUzZWJkNjYxM2FmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDE5MTE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1NmUxZTFhOGRjYjczYWU1ZjQ2NmIzMmI0YmY1ODkxNmI4NTM1NTY4YzY3MGRjY2RjNmYzMDM2ZjI2Y2MyNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-PL-GX2kuIFqHny4aTJsUu9A1tZZHYjO9NadH0xz_pM)



hello
I apologize for the delay in replying

Your problem is probably because the refresh rate of your monitor is not the highest possible
You should set the refresh rate of your monitor to the highest possible and if you need a frame limit, select the frame rate you need from the settings.

**Comment by bubuqing99** [comment]
> > 非常感谢您的贡献——您的程序实在太棒了。
> > 在此之前，我尝试过 SPV 和 Bluesky 帧速率转换器，但它们的效果都没有 MK-JH_Mpv-Fluid-Motion-Frames 好或完美。
> > 现在，我遇到了一个问题：当我测试 240p 和 480p 的视频时，未启用帧生成，我不确定这是否是一个错误。
> > 此外，当帧速率降至 30fps 以下时，伪影会变得严重，尤其是在带有窗户的视频中。
> > 非常感谢。
> > ![图像](https://private-user-images.githubusercontent.com/57699051/383852255-815194c6-c0aa-4939-b9e5-de6fd95d42da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MzkwMTgsIm5iZiI6MTczMTQzODcxOCwicGF0aCI6Ii81NzY5OTA1MS8zODM4NTIyNTUtODE1MTk0YzYtYzBhYS00OTM5LWI5ZTUtZGU2ZmQ5NWQ0MmRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDE5MTE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwNTU1MGY2NDRiODkxNGE4MDM5Yjc5MzlmNGNlMjlmOWJkMzViOWE3Y2E3N2E0ZTY1ZDUwY2JhNzU0NzcxNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nNwMuBti1Cg5c8n8lX3K5ZhzuFGYSsptRuT_0Vdd-VQ) ![图像](https://private-user-images.githubusercontent.com/57699051/383852267-5867ebce-1020-496f-9073-5e3ebd6613af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MzkwMTgsIm5iZiI6MTczMTQzODcxOCwicGF0aCI6Ii81NzY5OTA1MS8zODM4NTIyNjctNTg2N2ViY2UtMTAyMC00OTZmLTkwNzMtNWUzZWJkNjYxM2FmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDE5MTE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1NmUxZTFhOGRjYjczYWU1ZjQ2NmIzMmI0YmY1ODkxNmI4NTM1NTY4YzY3MGRjY2RjNmYzMDM2ZjI2Y2MyNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-PL-GX2kuIFqHny4aTJsUu9A1tZZHYjO9NadH0xz_pM)
> 
> 你好， 很抱歉这么晚才回复
> 
> 您的问题可能是因为您的显示器的刷新率不是最高的， 您应该将显示器的刷新率设置为最高，如果需要帧限制，请从设置中选择所需的帧速率。


https://github.com/user-attachments/assets/0169f145-999f-4835-a4ae-4306d76b4542

It’s not an issue with the monitor refresh rate; my display is set to 60 Hz by default. I think using a video would more intuitively show the difference. In this video, Frame Generation can be enabled when playing 720p videos, but when the resolution is 480p or lower, Frame Generation won’t activate.

**Comment by bubuqing99** [comment]
> > Thank you so much for your contribution—your program is truly amazing.
> > Before this, I tried SPV and Bluesky Frame Rate Converter, but neither of them worked as well or as perfectly as MK-JH_Mpv-Fluid-Motion-Frames.
> > Now, I’ve encountered an issue: when I tested videos at 240p and 480p, Frame Generation was not enabled, and I’m not sure if this is a bug.
> > Also, when the frame rate drops below 30fps, the artifacts become severe, especially in videos with windows.
> > Thank you very much.
> > ![image](https://private-user-images.githubusercontent.com/57699051/383852255-815194c6-c0aa-4939-b9e5-de6fd95d42da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MzkwMTgsIm5iZiI6MTczMTQzODcxOCwicGF0aCI6Ii81NzY5OTA1MS8zODM4NTIyNTUtODE1MTk0YzYtYzBhYS00OTM5LWI5ZTUtZGU2ZmQ5NWQ0MmRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDE5MTE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwNTU1MGY2NDRiODkxNGE4MDM5Yjc5MzlmNGNlMjlmOWJkMzViOWE3Y2E3N2E0ZTY1ZDUwY2JhNzU0NzcxNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nNwMuBti1Cg5c8n8lX3K5ZhzuFGYSsptRuT_0Vdd-VQ) ![image](https://private-user-images.githubusercontent.com/57699051/383852267-5867ebce-1020-496f-9073-5e3ebd6613af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MzkwMTgsIm5iZiI6MTczMTQzODcxOCwicGF0aCI6Ii81NzY5OTA1MS8zODM4NTIyNjctNTg2N2ViY2UtMTAyMC00OTZmLTkwNzMtNWUzZWJkNjYxM2FmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDE5MTE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1NmUxZTFhOGRjYjczYWU1ZjQ2NmIzMmI0YmY1ODkxNmI4NTM1NTY4YzY3MGRjY2RjNmYzMDM2ZjI2Y2MyNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-PL-GX2kuIFqHny4aTJsUu9A1tZZHYjO9NadH0xz_pM)
> 
> hello I apologize for the delay in replying
> 
> Your problem is probably because the refresh rate of your monitor is not the highest possible You should set the refresh rate of your m

https://github.com/user-attachments/assets/ee2e72b4-0a8a-4cc3-881f-2e5c9304faed

It’s not an issue with the monitor refresh rate; my display is set to 60 Hz by default. I think using a video would more intuitively show the difference. In this video, Frame Generation can be enabled when playing 720p videos, but when the resolution is 480p or lower, Frame Generation won’t activate.

**Comment by MK-JH** [comment]
> > > Thank you so much for your contribution—your program is truly amazing.
> > > Before this, I tried SPV and Bluesky Frame Rate Converter, but neither of them worked as well or as perfectly as MK-JH_Mpv-Fluid-Motion-Frames.
> > > Now, I’ve encountered an issue: when I tested videos at 240p and 480p, Frame Generation was not enabled, and I’m not sure if this is a bug.
> > > Also, when the frame rate drops below 30fps, the artifacts become severe, especially in videos with windows.
> > > Thank you very much.
> > > ![image](https://private-user-images.githubusercontent.com/57699051/383852255-815194c6-c0aa-4939-b9e5-de6fd95d42da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MzkwMTgsIm5iZiI6MTczMTQzODcxOCwicGF0aCI6Ii81NzY5OTA1MS8zODM4NTIyNTUtODE1MTk0YzYtYzBhYS00OTM5LWI5ZTUtZGU2ZmQ5NWQ0MmRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDE5MTE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwNTU1MGY2NDRiODkxNGE4MDM5Yjc5MzlmNGNlMjlmOWJkMzViOWE3Y2E3N2E0ZTY1ZDUwY2JhNzU0NzcxNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nNwMuBti1Cg5c8n8lX3K5ZhzuFGYSsptRuT_0Vdd-VQ) ![image](https://private-user-images.githubusercontent.com/57699051/383852267-5867ebce-1020-496f-9073-5e3ebd6613af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MzkwMTgsIm5iZiI6MTczMTQzODcxOCwicGF0aCI6Ii81NzY5OTA1MS8zODM4NTIyNjctNTg2N2ViY2UtMTAyMC00OTZmLTkwNzMtNWUzZWJkNjYxM2FmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDE5MTE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1NmUxZTFhOGRjYjczYWU1ZjQ2NmIzMmI0YmY1ODkxNmI4NTM1NTY4YzY3MGRjY2RjNmYzMDM2ZjI2Y2MyNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-PL-GX2kuIFqHny4aTJsUu9A1tZZHYjO9NadH0xz_pM)
> > 
> > 
> > hello I apologize for the delay in replying
> > Your problem is probably because the refresh rate of your monitor is not the highest possible You should set the refresh rate of your m
> 
>  bandicam.2024-11-13.11-49-27-101_2.mp4 
> It’s not an issue with the monitor refresh rate; my display is set to 60 Hz by default. I think using a video would more intuitively show the difference. In this video, Frame Generation can be enabled when playing 720p videos, but when the resolution is 480p or lower, Frame Generation won’t activate.

![mpv_2024_11_22_21_15_51_744](https://github.com/user-attachments/assets/be811a50-e310-4469-95e7-beb54d63391f)
![mpv_2024_11_22_21_16_35_443](https://github.com/user-attachments/assets/faa4d5f8-fb07-4c17-9fab-b76f4d005dbb)
